export const FILES_COPY = {
  searchPlaceholder: "Search files",
  clearSearch: "Clear search",
  searching: "Searching files...",
  searchFailed: "Search failed.",
  noMatches: "No results match your search.",
  loading: "Loading",
  empty: "Empty",
  noEnvironment: "This thread has no workspace yet.",
  noWorkspacePath: "This environment has no workspace path yet.",
  diskConflict: "This file changed on disk.",
  overwrite: "Overwrite",
  reload: "Reload",
  deletedOnDisk: "This file was deleted or moved.",
  recreate: "Recreate",
  retry: "Retry",
  unsaved: "Unsaved changes",
  saving: "Saving",
  copyPath: "Copy path",
  pathCopied: "Path copied",
  pathCopyFailed: "Failed to copy path",
  contentsCopied: "Contents copied",
  contentsCopyFailed: "Failed to copy contents",
  fileActions: "File actions",
  copyContents: "Copy contents",
  download: "Download",
  downloadFailed: "Failed to download file",
  openInEditor: "Open in editor",
  openExternally: "Open externally",
  delete: "Delete",
  cancel: "Cancel",
  wrapLines: "Wrap lines",
  source: "Code",
  unavailable: "File unavailable.",
  imageUnavailable:
    "Image preview unavailable. Use File actions to download it.",
  binaryFile: (name: string) => `Binary file · ${name}`,
  deleted: (name: string) => `${name} was deleted.`,
  deleteTitle: (name: string) => `Delete ${name}?`,
  deleteDescription:
    "This removes the file from disk. It cannot be undone from here.",
  markdown: {
    placeholder: "Press '/' for commands",
    noCommands: "No results",
    blockStyle: "Block style",
    text: "Text",
    heading1: "Heading 1",
    heading2: "Heading 2",
    heading3: "Heading 3",
    bulletList: "Bulleted list",
    orderedList: "Numbered list",
    quote: "Quote",
    codeBlock: "Code block",
    image: "Image",
    table: "Table",
    bold: "Bold",
    italic: "Italic",
    strike: "Strikethrough",
    code: "Code",
    clearFormatting: "Remove formatting",
    link: "Link",
    setLink: "Set link",
    removeLink: "Remove link",
    linkPlaceholder: "https://example.com",
    imagePlaceholder: "https://example.com/image.png",
    insertImage: "Insert image",
    cancelImage: "Cancel image",
    altText: "Image alt text",
    altPlaceholder: "Describe image",
    saveAlt: "Save alt text",
    removeAlt: "Remove alt text",
    rows: "Rows:",
    columns: "Columns:",
    addRow: "Add row",
    removeRow: "Remove row",
    addColumn: "Add column",
    removeColumn: "Remove column",
    addToChat: "Add to chat",
  },
} as const;
