import {
  RiAddBoxLine,
  RiAddLine,
  RiAlignLeft,
  RiArrowDownDoubleLine,
  RiArrowDownLine,
  RiArrowGoBackLine,
  RiArrowGoForwardLine,
  RiArrowLeftLine,
  RiArrowRightBoxLine,
  RiArrowRightLine,
  RiArrowRightUpLine,
  RiArrowUpDoubleLine,
  RiArrowUpDownLine,
  RiArrowUpLine,
  RiArrowUpSLine,
  RiAttachment2,
  RiBarChart2Line,
  RiBookOpenLine,
  RiBox3Line,
  RiBrainLine,
  RiCalendarCheckLine,
  RiCalendarLine,
  RiCalendarScheduleLine,
  RiChatThreadLine,
  RiCheckboxBlankLine,
  RiCloudLine,
  RiCloudOffLine,
  RiCollapseDiagonalLine,
  RiConnectorLine,
  RiCornerDownLeftLine,
  RiCornerDownRightLine,
  RiCupLine,
  RiDashboard3Line,
  RiDiscordFill,
  RiDiscordLine,
  RiDraggable,
  RiEditBoxLine,
  RiEraserLine,
  RiExpandDiagonalLine,
  RiExternalLinkLine,
  RiEyeLine,
  RiEyeOffLine,
  RiFileChartLine,
  RiFileEditLine,
  RiFileLine,
  RiFileSearchLine,
  RiFileTextLine,
  RiFlaskLine,
  RiFolderOpenLine,
  RiFolderReduceLine,
  RiGitBranchLine,
  RiGitClosePullRequestLine,
  RiGitForkLine,
  RiGitMergeLine,
  RiGitPrDraftLine,
  RiGitPullRequestLine,
  RiGithubFill,
  RiGithubLine,
  RiGlobalLine,
  RiInboxUnarchiveLine,
  RiLayoutBottom2Line,
  RiLayoutColumnLine,
  RiLayoutGridLine,
  RiLayoutRight2Line,
  RiLayoutRowLine,
  RiListView,
  RiLockLine,
  RiLockUnlockLine,
  RiLoopLeftLine,
  RiLoopRightLine,
  RiMacbookLine,
  RiMailLine,
  RiMailOpenLine,
  RiMicLine,
  RiNewspaperLine,
  RiNotificationBadgeLine,
  RiPaletteLine,
  RiPauseLine,
  RiPlayLine,
  RiPlayListLine,
  RiPlug2Line,
  RiPlugLine,
  RiRobot3Line,
  RiStopFill,
  RiPushpinLine,
  RiResetLeftLine,
  RiSendPlaneLine,
  RiShieldCheckLine,
  RiSmartphoneLine,
  RiSortAlphabetAsc,
  RiSortAlphabetDesc,
  RiSortAsc,
  RiSortDesc,
  RiSortNumberAsc,
  RiSortNumberDesc,
  RiSparkling2Line,
  RiStackLine,
  RiStarLine,
  RiSubtractLine,
  RiTextWrap,
  RiTimeLine,
  RiTimerLine,
  RiUnpinLine,
  RiUserLine,
  RiWindow2Line,
  RiWindowLine,
  RiZoomInLine,
  RiZoomOutLine,
} from "react-icons/ri";
import { type ExtendedIconMap, registerExtendedIcons } from "./icon-registry";

export const EXTENDED_ICON_MAP: ExtendedIconMap = {
  AiBrain01: RiBrainLine,
  AiBrowser: RiWindowLine,
  AiContentGenerator01: RiSparkling2Line,
  AlignLeft: RiAlignLeft,
  AppWindow: RiWindow2Line,
  ArchiveRestore: RiInboxUnarchiveLine,
  ArrowDown: RiArrowDownLine,
  ArrowLeft: RiArrowLeftLine,
  ArrowRight: RiArrowRightLine,
  ArrowReloadHorizontal: RiLoopRightLine,
  ArrowUp: RiArrowUpLine,
  ArrowUpDown: RiArrowUpDownLine,
  ArrowTurnBackward: RiArrowGoBackLine,
  ArrowTurnForward: RiArrowGoForwardLine,
  ArrowUpRight: RiArrowRightUpLine,
  Beaker: RiFlaskLine,
  BellDot: RiNotificationBadgeLine,
  Browser: RiWindowLine,
  Brain: RiBrainLine,
  Calendar: RiCalendarLine,
  CalendarCheckOut02: RiCalendarCheckLine,
  ChartColumn: RiBarChart2Line,
  ChevronUp: RiArrowUpSLine,
  ChevronsDown: RiArrowDownDoubleLine,
  ChevronsUp: RiArrowUpDoubleLine,
  CircleArrowShrink: RiCollapseDiagonalLine,
  Clean: RiEraserLine,
  Clock: RiTimeLine,
  ClockArrowUp: RiSortAsc,
  ClockArrowDown: RiSortDesc,
  Cloud: RiCloudLine,
  CloudOff: RiCloudOffLine,
  Coffee: RiCupLine,
  Columns2: RiLayoutColumnLine,
  CornerDownLeft: RiCornerDownLeftLine,
  CornerDownRight: RiCornerDownRightLine,
  Discord: RiDiscordLine,
  DiscordLogo: RiDiscordFill,
  DateTime: RiCalendarScheduleLine,
  Github: RiGithubLine,
  GithubLogo: RiGithubFill,
  DragDropHorizontal: RiDraggable,
  DragDropVertical: RiDraggable,
  EditFile: RiFileEditLine,
  ElectricPlugs: RiPlug2Line,
  Eye: RiEyeLine,
  EyeOff: RiEyeOffLine,
  Explore: RiBookOpenLine,
  ExternalLink: RiExternalLinkLine,
  FileDiff: RiFileChartLine,
  File: RiFileLine,
  FileAttachment: RiAttachment2,
  FileQuestion: RiFileSearchLine,
  FileText: RiFileTextLine,
  FolderOpen: RiFolderOpenLine,
  FolderEdit: RiEditBoxLine,
  FolderMinus: RiFolderReduceLine,
  Fork: RiGitForkLine,
  GitBranch: RiGitBranchLine,
  GitMerge: RiGitMergeLine,
  GitPullRequest: RiGitPullRequestLine,
  GitPullRequestArrow: RiGitPullRequestLine,
  GitPullRequestClosed: RiGitClosePullRequestLine,
  GitPullRequestDraft: RiGitPrDraftLine,
  Globe: RiGlobalLine,
  GridView: RiLayoutGridLine,
  Laptop: RiMacbookLine,
  Layers: RiStackLine,
  Limitation: RiDashboard3Line,
  ListEnd: RiPlayListLine,
  ListView: RiListView,
  Lock: RiLockLine,
  Mail: RiMailLine,
  MailOpen: RiMailOpenLine,
  Maximize2: RiExpandDiagonalLine,
  Mic: RiMicLine,
  Minus: RiSubtractLine,
  Minimize2: RiCollapseDiagonalLine,
  MoveTo: RiArrowRightBoxLine,
  NewTab: RiAddBoxLine,
  News01: RiNewspaperLine,
  PackageReceive: RiBox3Line,
  Palette: RiPaletteLine,
  PanelBottom: RiLayoutBottom2Line,
  PanelRight: RiLayoutRight2Line,
  Paperclip: RiAttachment2,
  Pause: RiPauseLine,
  Pin: RiPushpinLine,
  PinOff: RiUnpinLine,
  Play: RiPlayLine,
  Plug02: RiPlugLine,
  Connector: RiConnectorLine,
  Robot: RiRobot3Line,
  StopFill: RiStopFill,
  EditBox: RiEditBoxLine,
  Plus: RiAddLine,
  Repeat: RiLoopLeftLine,
  SecurityCheck: RiShieldCheckLine,
  RotateCcw: RiResetLeftLine,
  Rows2: RiLayoutRowLine,
  Sent: RiSendPlaneLine,
  SideChat: RiChatThreadLine,
  Smartphone: RiSmartphoneLine,
  Sort: RiArrowUpDownLine,
  SortingAZ02: RiSortAlphabetAsc,
  SortingZA01: RiSortAlphabetDesc,
  SortingOneNine: RiSortNumberAsc,
  SortingNineOne: RiSortNumberDesc,
  Square: RiCheckboxBlankLine,
  SquareUnlock02: RiLockUnlockLine,
  Star: RiStarLine,
  TextWrap: RiTextWrap,
  TimeSchedule: RiTimerLine,
  UserRound: RiUserLine,
  ZoomIn: RiZoomInLine,
  ZoomOut: RiZoomOutLine,
};

registerExtendedIcons(EXTENDED_ICON_MAP);
