import {
  PiAppWindowBold,
  PiArrowCounterClockwiseBold,
  PiArrowDownBold,
  PiArrowElbowDownLeftBold,
  PiArrowElbowDownRightBold,
  PiArrowLeftBold,
  PiArrowRightBold,
  PiArrowSquareOutBold,
  PiArrowSquareRightBold,
  PiArrowUDownLeftBold,
  PiArrowUUpLeftBold,
  PiArrowUUpRightBold,
  PiArrowUpBold,
  PiArrowUpRightBold,
  PiArrowsClockwiseBold,
  PiArrowsDownUpBold,
  PiArrowsInBold,
  PiArrowsOutBold,
  PiBellRingingBold,
  PiBookOpenBold,
  PiBoxArrowUpBold,
  PiBrainBold,
  PiBroomBold,
  PiBrowserBold,
  PiCalendarBlankBold,
  PiCalendarCheckBold,
  PiCalendarDotsBold,
  PiCaretDoubleDownBold,
  PiCaretDoubleUpBold,
  PiCaretUpBold,
  PiChartBarBold,
  PiChatsCircleBold,
  PiClockBold,
  PiClockClockwiseBold,
  PiClockCountdownBold,
  PiClockCounterClockwiseBold,
  PiCloudBold,
  PiCloudSlashBold,
  PiCoffeeBold,
  PiColumnsBold,
  PiDeviceMobileBold,
  PiDiscordLogoBold,
  PiDiscordLogoFill,
  PiDotsSixBold,
  PiDotsSixVerticalBold,
  PiEnvelopeBold,
  PiEnvelopeOpenBold,
  PiEyeBold,
  PiEyeSlashBold,
  PiFileArrowUpBold,
  PiFileBold,
  PiFileMagnifyingGlassBold,
  PiFileTextBold,
  PiFlaskBold,
  PiFolderOpenBold,
  PiFolderSimpleMinusBold,
  PiGaugeBold,
  PiGitBranchBold,
  PiGitForkBold,
  PiGitMergeBold,
  PiGitPullRequestBold,
  PiGithubLogoBold,
  PiGithubLogoFill,
  PiGlobeBold,
  PiLaptopBold,
  PiListBold,
  PiLockBold,
  PiLockSimpleOpenBold,
  PiMagnifyingGlassMinusBold,
  PiMagnifyingGlassPlusBold,
  PiMicrophoneBold,
  PiMinusBold,
  PiNewspaperBold,
  PiPackageBold,
  PiPaletteBold,
  PiPaperPlaneTiltBold,
  PiPaperclipBold,
  PiPauseBold,
  PiPencilLineBold,
  PiPencilSimpleLineBold,
  PiPlayBold,
  PiPlugsBold,
  PiPlugsConnectedBold,
  PiPlusBold,
  PiPlusMinusBold,
  PiPlusSquareBold,
  PiPushPinBold,
  PiPushPinSlashBold,
  PiPuzzlePieceBold,
  PiQueueBold,
  PiRepeatBold,
  PiRowsBold,
  PiShieldCheckBold,
  PiSortAscendingBold,
  PiSortDescendingBold,
  PiSparkleBold,
  PiSquareBold,
  PiSquareHalfBold,
  PiSquareHalfBottomBold,
  PiSquaresFourBold,
  PiStackBold,
  PiStarBold,
  PiTextAlignLeftBold,
  PiUserBold,
} from "react-icons/pi";
import { type ExtendedIconMap, registerExtendedIcons } from "./icon-registry";

export const EXTENDED_ICON_MAP: ExtendedIconMap = {
  AiBrain01: PiBrainBold,
  AiBrowser: PiBrowserBold,
  AiContentGenerator01: PiSparkleBold,
  AlignLeft: PiTextAlignLeftBold,
  AppWindow: PiAppWindowBold,
  ArchiveRestore: PiBoxArrowUpBold,
  ArrowDown: PiArrowDownBold,
  ArrowLeft: PiArrowLeftBold,
  ArrowRight: PiArrowRightBold,
  ArrowReloadHorizontal: PiArrowsClockwiseBold,
  ArrowUp: PiArrowUpBold,
  ArrowUpDown: PiArrowsDownUpBold,
  ArrowTurnBackward: PiArrowUUpLeftBold,
  ArrowTurnForward: PiArrowUUpRightBold,
  ArrowUpRight: PiArrowUpRightBold,
  Beaker: PiFlaskBold,
  BellDot: PiBellRingingBold,
  Browser: PiBrowserBold,
  Brain: PiBrainBold,
  Calendar: PiCalendarBlankBold,
  CalendarCheckOut02: PiCalendarCheckBold,
  ChartColumn: PiChartBarBold,
  ChevronUp: PiCaretUpBold,
  ChevronsDown: PiCaretDoubleDownBold,
  ChevronsUp: PiCaretDoubleUpBold,
  CircleArrowShrink: PiArrowsInBold,
  Clean: PiBroomBold,
  Clock: PiClockBold,
  ClockArrowUp: PiClockClockwiseBold,
  ClockArrowDown: PiClockCounterClockwiseBold,
  Cloud: PiCloudBold,
  CloudOff: PiCloudSlashBold,
  Coffee: PiCoffeeBold,
  Columns2: PiColumnsBold,
  CornerDownLeft: PiArrowElbowDownLeftBold,
  CornerDownRight: PiArrowElbowDownRightBold,
  Discord: PiDiscordLogoBold,
  DiscordLogo: PiDiscordLogoFill,
  DateTime: PiCalendarDotsBold,
  Github: PiGithubLogoBold,
  GithubLogo: PiGithubLogoFill,
  DragDropHorizontal: PiDotsSixBold,
  DragDropVertical: PiDotsSixVerticalBold,
  EditFile: PiPencilLineBold,
  ElectricPlugs: PiPlugsBold,
  Eye: PiEyeBold,
  EyeOff: PiEyeSlashBold,
  Explore: PiBookOpenBold,
  ExternalLink: PiArrowSquareOutBold,
  FileDiff: PiPlusMinusBold,
  File: PiFileBold,
  FileAttachment: PiFileArrowUpBold,
  FileQuestion: PiFileMagnifyingGlassBold,
  FileText: PiFileTextBold,
  FolderOpen: PiFolderOpenBold,
  FolderEdit: PiPencilSimpleLineBold,
  FolderMinus: PiFolderSimpleMinusBold,
  Fork: PiGitForkBold,
  GitBranch: PiGitBranchBold,
  GitMerge: PiGitMergeBold,
  GitPullRequest: PiGitPullRequestBold,
  GitPullRequestArrow: PiGitPullRequestBold,
  GitPullRequestClosed: PiGitPullRequestBold,
  GitPullRequestDraft: PiGitPullRequestBold,
  Globe: PiGlobeBold,
  GridView: PiSquaresFourBold,
  Laptop: PiLaptopBold,
  Layers: PiStackBold,
  Limitation: PiGaugeBold,
  ListEnd: PiQueueBold,
  ListView: PiListBold,
  Lock: PiLockBold,
  Mail: PiEnvelopeBold,
  MailOpen: PiEnvelopeOpenBold,
  Maximize2: PiArrowsOutBold,
  Mic: PiMicrophoneBold,
  Minus: PiMinusBold,
  Minimize2: PiArrowsInBold,
  MoveTo: PiArrowSquareRightBold,
  NewTab: PiPlusSquareBold,
  News01: PiNewspaperBold,
  PackageReceive: PiPackageBold,
  Palette: PiPaletteBold,
  PanelBottom: PiSquareHalfBottomBold,
  PanelRight: PiSquareHalfBold,
  Paperclip: PiPaperclipBold,
  Pause: PiPauseBold,
  Pin: PiPushPinBold,
  PinOff: PiPushPinSlashBold,
  Play: PiPlayBold,
  Plug02: PiPlugsConnectedBold,
  Plus: PiPlusBold,
  Puzzle: PiPuzzlePieceBold,
  Repeat: PiRepeatBold,
  SecurityCheck: PiShieldCheckBold,
  RotateCcw: PiArrowCounterClockwiseBold,
  Rows2: PiRowsBold,
  Sent: PiPaperPlaneTiltBold,
  SideChat: PiChatsCircleBold,
  Smartphone: PiDeviceMobileBold,
  Sort: PiSortAscendingBold,
  SortingAZ02: PiSortAscendingBold,
  SortingZA01: PiSortDescendingBold,
  SortingOneNine: PiSortAscendingBold,
  SortingNineOne: PiSortDescendingBold,
  Square: PiSquareBold,
  SquareUnlock02: PiLockSimpleOpenBold,
  Star: PiStarBold,
  TextWrap: PiArrowUDownLeftBold,
  TimeSchedule: PiClockCountdownBold,
  UserRound: PiUserBold,
  ZoomIn: PiMagnifyingGlassPlusBold,
  ZoomOut: PiMagnifyingGlassMinusBold,
};

registerExtendedIcons(EXTENDED_ICON_MAP);
